//! Aurum Studio's local shell: a loopback-only HTTP and event-stream server,
//! written on `std::net` with no web framework.
//!
//! Godot stays the workhorse. This is the part that gives a person — and an AI
//! driving the same surface — a view of what Studio is doing: whether the
//! project is healthy, what a build is producing, which processes Studio owns,
//! and what happened, as it happens.
//!
//! ## Why a server and a browser rather than a window
//!
//! A native toolkit is a very large dependency tree, and every crate in it is
//! code that runs with the user's privileges. A local server costs no new
//! packages at all, and it has a property a window does not: it is a plain
//! HTTP interface, so tests can drive it, scripts can drive it, and an AI can
//! drive it. The shell stops being human-only.
//!
//! ## The threat model, stated plainly
//!
//! A server on the loopback interface is reachable by every process on the
//! machine, and by any web page the user's browser loads. Three things keep
//! that from being a way to run commands on this machine:
//!
//! 1. **It binds `127.0.0.1`, never `0.0.0.0`.** The port is not reachable
//!    from the network at all. This is the difference between a local tool and
//!    an open door, so it is not configurable.
//! 2. **Every request needs the session token**, which is 256 bits from the
//!    operating system's generator and is compared in constant time. A page
//!    that guesses is not slowed down; it is simply wrong.
//! 3. **The `Host` header must be a loopback literal.** This is the
//!    DNS-rebinding defence: a hostile page can point its own domain at
//!    `127.0.0.1`, and the browser will then send requests here with that
//!    domain in `Host`. Refusing a non-loopback `Host` means the rebind fails
//!    before the token is even considered.
//!
//! The token is passed in the URL so the browser can be opened directly, and
//! the page's first act is to move it into `sessionStorage` and strip it from
//! the address bar, so it does not linger in history or leak in a `Referer`.

pub mod assets;
pub mod http;
mod preview;

use std::io::{BufReader, Write};
use std::net::{IpAddr, Ipv4Addr, SocketAddr, TcpListener, TcpStream};
use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
use std::sync::mpsc::{self, Receiver, Sender};
use std::sync::{Arc, Mutex};
use std::time::Duration;

use aurum_studio_core::supervisor::{Command, Event, Supervisor, SupervisorConfig};
use aurum_studio_core::Project;

use http::{Request, Response};

/// The most connections served at once.
///
/// A browser opens a handful, and each event stream holds one for as long as
/// the page is open. The ceiling exists so a process that opens sockets in a
/// loop cannot make this server spawn threads without limit.
pub const MAX_CONNECTIONS: usize = 64;

/// How long a client has to send its request.
pub const READ_TIMEOUT: Duration = Duration::from_secs(30);

/// How often the accept loop checks whether it has been asked to stop.
const ACCEPT_POLL: Duration = Duration::from_millis(100);

/// How long an event stream waits before sending a keep-alive comment.
///
/// Idle connections are closed by intermediaries and by browsers, and a
/// comment line keeps the stream demonstrably alive without waking the page.
const KEEPALIVE: Duration = Duration::from_secs(15);

/// What the server needs to start.
pub struct ServerConfig {
    pub project: Project,
    pub godot_hint: Option<PathBuf>,
    /// The port to bind. Zero asks the operating system for a free one.
    pub port: u16,
    /// The session token. Generated by [`Server::bind`] when empty.
    pub token: String,
}

impl ServerConfig {
    pub fn new(project: Project) -> Self {
        Self {
            project,
            godot_hint: None,
            port: 0,
            token: String::new(),
        }
    }
}

/// A running shell server.
pub struct Server {
    listener: TcpListener,
    shell: Arc<Shell>,
    address: SocketAddr,
}

/// What every connection handler needs.
///
/// Bundled rather than passed as seven arguments, and cloned per connection
/// because each one is an `Arc` bump.
#[derive(Clone)]
struct Shell {
    token: String,
    project_name: String,
    project_root: String,
    selected_root: Arc<Mutex<PathBuf>>,
    supervisor: Arc<Supervisor>,
    hub: Arc<Hub>,
    running: Arc<AtomicBool>,
    connections: Arc<AtomicUsize>,
    operations: Arc<AtomicUsize>,
    port: u16,
    godot_hint: Option<PathBuf>,
    preview: Arc<Mutex<Option<preview::Preview>>>,
    fallback_preview: Arc<Mutex<Option<preview::Preview>>>,
    preview_epoch: Arc<AtomicUsize>,
}

impl Server {
    /// Bind the listener and start the supervisor.
    ///
    /// Binding is separate from serving so a caller can learn the port — and
    /// so tests can drive a real server on a real socket.
    pub fn bind(config: ServerConfig) -> std::io::Result<Self> {
        // `127.0.0.1` explicitly. Binding the unspecified address would expose
        // process control to the whole network.
        let listener = TcpListener::bind((Ipv4Addr::LOCALHOST, config.port))?;
        // Non-blocking so the accept loop can notice a shutdown request
        // instead of parking until the next connection arrives.
        listener.set_nonblocking(true)?;
        let address = listener.local_addr()?;

        let token = if config.token.is_empty() {
            new_token()
        } else {
            config.token
        };

        let project_name = config.project.config.name.clone();
        let project_root = config.project.root.display().to_string();
        let selected_root = Arc::new(Mutex::new(config.project.root.clone()));

        let supervisor = Arc::new(Supervisor::start(SupervisorConfig::new(
            config.project,
            config.godot_hint.clone(),
        )));

        let hub = Arc::new(Hub::default());
        let running = Arc::new(AtomicBool::new(true));

        // One thread drains the supervisor and fans the events out. The
        // supervisor's queue has a single consumer, so this is the only place
        // they are taken from; every connected page is a subscriber to the hub
        // instead.
        spawn_pump(
            Arc::clone(&supervisor),
            Arc::clone(&hub),
            Arc::clone(&running),
        );

        Ok(Self {
            listener,
            shell: Arc::new(Shell {
                token,
                project_name,
                project_root,
                selected_root,
                supervisor,
                hub,
                running,
                connections: Arc::new(AtomicUsize::new(0)),
                operations: Arc::new(AtomicUsize::new(0)),
                port: address.port(),
                godot_hint: config.godot_hint,
                preview: Arc::new(Mutex::new(None)),
                fallback_preview: Arc::new(Mutex::new(None)),
                preview_epoch: Arc::new(AtomicUsize::new(0)),
            }),
            address,
        })
    }

    pub fn local_addr(&self) -> SocketAddr {
        self.address
    }

    pub fn port(&self) -> u16 {
        self.address.port()
    }

    pub fn token(&self) -> &str {
        &self.shell.token
    }

    /// The address to open in a browser, token included.
    pub fn url(&self) -> String {
        format!("http://127.0.0.1:{}/?t={}", self.port(), self.token())
    }

    /// Serve until [`Server::stop`] is called.
    pub fn serve(&self) {
        while self.shell.running.load(Ordering::SeqCst) {
            match self.listener.accept() {
                Ok((stream, _peer)) => {
                    if self.shell.connections_count() >= MAX_CONNECTIONS {
                        // Refused rather than queued: the ceiling is the
                        // point, and a slow refusal costs nothing.
                        let mut stream = stream;
                        let _ =
                            Response::error(503, "too many connections\n").write_to(&mut stream);
                        continue;
                    }
                    self.shell.connections_add();

                    let shell = Arc::clone(&self.shell);

                    // A thread per connection is the right shape here: there
                    // are at most `MAX_CONNECTIONS`, and each is idle almost
                    // all of the time.
                    std::thread::spawn(move || {
                        handle_connection(stream, &shell);
                        shell.connections_sub();
                    });
                }
                Err(error) if error.kind() == std::io::ErrorKind::WouldBlock => {
                    std::thread::sleep(ACCEPT_POLL);
                }
                Err(error) if error.kind() == std::io::ErrorKind::Interrupted => continue,
                Err(_) => {
                    // A failure to accept is not necessarily fatal, so the
                    // loop continues rather than taking the shell down.
                    std::thread::sleep(ACCEPT_POLL);
                }
            }
        }
        while self.shell.operations.load(Ordering::SeqCst) > 0 {
            std::thread::sleep(Duration::from_millis(20));
        }
        self.shell
            .preview
            .lock()
            .unwrap_or_else(|e| e.into_inner())
            .take();
        self.shell.supervisor.wait_for_shutdown();
        self.shell
            .fallback_preview
            .lock()
            .unwrap_or_else(|e| e.into_inner())
            .take();
    }

    /// Ask the accept loop to finish.
    ///
    /// Safe to call from another thread, and safe to call more than once.
    pub fn stop(&self) {
        self.shell.running.store(false, Ordering::SeqCst);
    }

    /// A handle that can stop the server from another thread.
    pub fn stopper(&self) -> Stopper {
        Stopper {
            running: Arc::clone(&self.shell.running),
        }
    }
}

/// Stops a server from another thread.
#[derive(Clone)]
pub struct Stopper {
    running: Arc<AtomicBool>,
}

impl Stopper {
    pub fn stop(&self) {
        self.running.store(false, Ordering::SeqCst);
    }
}

impl Shell {
    fn connections_count(&self) -> usize {
        self.connections.load(Ordering::SeqCst)
    }

    fn connections_add(&self) {
        self.connections.fetch_add(1, Ordering::SeqCst);
    }

    fn connections_sub(&self) {
        // Saturating: a handler that ran without an increment must not wrap
        // the counter to a huge number and permanently refuse connections.
        let mut count = self.connections.load(Ordering::SeqCst);
        loop {
            match self.connections.compare_exchange_weak(
                count,
                count.saturating_sub(1),
                Ordering::SeqCst,
                Ordering::SeqCst,
            ) {
                Ok(_) => break,
                Err(current) => count = current,
            }
        }
    }
}

/// A 256-bit token from the operating system's generator.
fn new_token() -> String {
    aurum_studio_core::random::token()
}

/// Compare two secrets without leaking where they differ.
///
/// A comparison that stops at the first wrong byte tells an attacker how much
/// of a guess was right, one byte at a time. Comparing every byte costs
/// nothing here.
fn constant_time_eq(a: &str, b: &str) -> bool {
    let (a, b) = (a.as_bytes(), b.as_bytes());
    if a.len() != b.len() {
        return false;
    }
    let mut difference = 0u8;
    for (left, right) in a.iter().zip(b.iter()) {
        difference |= left ^ right;
    }
    difference == 0
}

// -- fan-out --------------------------------------------------------------

/// Every connected event stream.
#[derive(Default)]
struct Hub {
    clients: Mutex<Vec<Client>>,
    next_id: AtomicUsize,
}

struct Client {
    id: usize,
    sender: Sender<Event>,
}

impl Hub {
    /// Add a subscriber, returning its id and receiver.
    fn subscribe(self: &Arc<Self>) -> (usize, Receiver<Event>) {
        let (sender, receiver) = mpsc::channel();
        let id = self.next_id.fetch_add(1, Ordering::SeqCst);
        let mut clients = self.clients.lock().unwrap_or_else(|e| e.into_inner());
        clients.push(Client { id, sender });
        (id, receiver)
    }

    fn unsubscribe(&self, id: usize) {
        let mut clients = self.clients.lock().unwrap_or_else(|e| e.into_inner());
        clients.retain(|client| client.id != id);
    }

    /// Send to every subscriber, dropping any that have gone away.
    fn broadcast(&self, event: &Event) {
        let mut clients = self.clients.lock().unwrap_or_else(|e| e.into_inner());
        clients.retain(|client| client.sender.send(event.clone()).is_ok());
    }
}

/// Drain the supervisor once, fanning events out to every page.
fn spawn_pump(supervisor: Arc<Supervisor>, hub: Arc<Hub>, running: Arc<AtomicBool>) {
    std::thread::spawn(move || {
        while running.load(Ordering::SeqCst) {
            match supervisor.recv_timeout(Duration::from_millis(200)) {
                Some(Event::Stopped) => {
                    hub.broadcast(&Event::Stopped);
                    break;
                }
                Some(event) => hub.broadcast(&event),
                None => {}
            }
        }
    });
}

// -- connections ----------------------------------------------------------

fn handle_connection(stream: TcpStream, shell: &Arc<Shell>) {
    let _ = stream.set_nonblocking(false);
    let _ = stream.set_read_timeout(Some(READ_TIMEOUT));
    let _ = stream.set_write_timeout(Some(READ_TIMEOUT));
    let _ = stream.set_nodelay(true);

    let mut writer = match stream.try_clone() {
        Ok(clone) => clone,
        Err(_) => return,
    };
    let mut reader = BufReader::new(stream);

    let request = match http::read_request(&mut reader) {
        Ok(Some(request)) => request,
        Ok(None) => return,
        Err(error) => {
            let _ = Response::error(error.status(), format!("{error}\n")).write_to(&mut writer);
            return;
        }
    };

    // Order matters: the loopback check runs before the token check, so a
    // rebound request is refused without the token being compared at all.
    if let Err(response) = check_local(&request) {
        let _ = response.write_to(&mut writer);
        return;
    }
    if let Err(response) = check_origin(&request, shell.port) {
        let _ = response.write_to(&mut writer);
        return;
    }
    if let Err(response) = check_token(&request, &shell.token) {
        let _ = response.write_to(&mut writer);
        return;
    }

    match route(&request, shell) {
        Routed::Once(mut response) => {
            response
                .headers
                .push(("X-Frame-Options".into(), "DENY".into()));
            response
                .headers
                .push(("X-Content-Type-Options".into(), "nosniff".into()));
            // A token that arrived in the URL was a one-off navigation. The
            // page's own stylesheet and script requests cannot repeat it, so
            // the token is planted where the browser will send it by itself.
            if request
                .query_value("t")
                .is_some_and(|value| !value.is_empty())
            {
                response
                    .headers
                    .push(("Set-Cookie".into(), session_cookie(&shell.token)));
            }
            let _ = response.write_to(&mut writer);
        }
        Routed::Stream { id, receiver } => {
            let _ = stream_events(&mut writer, receiver, &shell.running);
            // Removed as soon as the page goes away, rather than lingering
            // until the next broadcast happens to notice.
            shell.hub.unsubscribe(id);
        }
    }
}

/// Refuse anything whose `Host` is not the loopback interface.
fn check_local(request: &Request) -> Result<(), Response> {
    let Some(host) = request.header("host") else {
        // HTTP/1.1 requires `Host`, and without it there is nothing to check,
        // so the request cannot be trusted to have come from this page.
        return Err(Response::error(400, "missing Host header\n"));
    };

    let hostname = match host.rsplit_once(':') {
        // An IPv6 literal is bracketed, and its colons are inside the
        // brackets, so a trailing colon split is only right for IPv4 and
        // names — which is all this server binds.
        Some((name, port)) if port.chars().all(|c| c.is_ascii_digit()) => name,
        _ => host,
    };
    let hostname = hostname.trim_start_matches('[').trim_end_matches(']');

    let is_loopback = hostname == "localhost"
        || hostname
            .parse::<IpAddr>()
            .map(|address| address.is_loopback())
            .unwrap_or(false);

    if is_loopback {
        Ok(())
    } else {
        Err(Response::error(
            403,
            "this server only answers requests addressed to the loopback interface\n",
        ))
    }
}

fn check_origin(request: &Request, port: u16) -> Result<(), Response> {
    if let Some(origin) = request.header("origin") {
        if origin != format!("http://127.0.0.1:{port}")
            && origin != format!("http://localhost:{port}")
        {
            return Err(Response::error(
                403,
                "Cross-origin control requests are refused\n",
            ));
        }
    }
    if request.method != "GET"
        && request.method != "HEAD"
        && matches!(
            request.header("sec-fetch-site"),
            Some("cross-site" | "same-site")
        )
    {
        return Err(Response::error(403, "Cross-origin mutations are refused\n"));
    }
    Ok(())
}

/// The cookie the page's own subresource requests carry.
pub const TOKEN_COOKIE: &str = "aurum_session";

/// Require the session token.
///
/// Three places are accepted, in order of how deliberate they are:
///
/// 1. `X-Aurum-Token`, which is what the page's own `fetch` calls send, and
///    what a script or an AI driving the API should send.
/// 2. `?t=`, which exists only so the browser can be opened at a URL. That is
///    the one navigation a browser makes without being told to.
/// 3. The session cookie, which is what makes the page actually work. A
///    browser fetches the stylesheet and the script as separate requests, and
///    those carry no query string and no custom header — only cookies. Without
///    this the page loads and renders as unstyled text.
///
/// An empty value counts as absent rather than as a wrong token, so a page
/// that has no token to offer falls through to the cookie instead of failing
/// on a header it sent out of habit.
fn check_token(request: &Request, token: &str) -> Result<(), Response> {
    let presented = request
        .header("x-aurum-token")
        .filter(|value| !value.is_empty())
        .or_else(|| request.query_value("t").filter(|value| !value.is_empty()))
        .or_else(|| {
            request
                .cookie(TOKEN_COOKIE)
                .filter(|value| !value.is_empty())
        });

    match presented {
        Some(presented) if constant_time_eq(presented, token) => Ok(()),
        Some(_) => Err(Response::error(401, "invalid token\n")),
        None => Err(Response::error(401, "missing token\n")),
    }
}

/// The `Set-Cookie` that lets the page fetch its own assets.
///
/// `HttpOnly` because nothing in the page needs to read it — the script keeps
/// its own copy for the header — and a token that JavaScript cannot read is a
/// token an injected script cannot steal. `SameSite=Strict` because every
/// request this server wants is same-origin, so a cross-site one arriving with
/// the cookie is by definition not something to honour.
fn session_cookie(token: &str) -> String {
    format!("{TOKEN_COOKIE}={token}; Path=/; SameSite=Strict; HttpOnly")
}

enum Routed {
    Once(Response),
    /// A long-lived stream, carrying the subscriber's id so it can be removed
    /// from the hub the moment it ends.
    Stream {
        id: usize,
        receiver: Receiver<Event>,
    },
}

struct Operation(Arc<AtomicUsize>);
impl Drop for Operation {
    fn drop(&mut self) {
        self.0.fetch_sub(1, Ordering::SeqCst);
    }
}

fn route(request: &Request, shell: &Arc<Shell>) -> Routed {
    let _operation = if request.method == "POST" && request.path != "/api/stop" {
        shell.operations.fetch_add(1, Ordering::SeqCst);
        let guard = Operation(Arc::clone(&shell.operations));
        if !shell.running.load(Ordering::SeqCst) {
            return Routed::Once(Response::error(503, "Studio is stopping"));
        }
        Some(guard)
    } else {
        None
    };
    match (request.method.as_str(), request.path.as_str()) {
        ("GET", "/") | ("GET", "/index.html") => Routed::Once(
            Response::html(assets::INDEX_HTML)
                .with_header("Cache-Control", "no-store")
                .with_header("Cross-Origin-Opener-Policy", "same-origin")
                .with_header("Cross-Origin-Embedder-Policy", "require-corp"),
        ),
        ("GET", "/app.js") => Routed::Once(
            Response::new(200, "text/javascript; charset=utf-8", assets::APP_JS)
                .with_header("Cache-Control", "no-store"),
        ),
        ("GET", "/style.css") => Routed::Once(
            Response::new(200, "text/css; charset=utf-8", assets::STYLE_CSS)
                .with_header("Cache-Control", "no-store"),
        ),
        ("GET", "/workspace.js") => Routed::Once(
            Response::new(200, "text/javascript; charset=utf-8", assets::WORKSPACE_JS)
                .with_header("Cache-Control", "no-store"),
        ),
        ("GET", "/workspace.css") => Routed::Once(
            Response::new(200, "text/css; charset=utf-8", assets::WORKSPACE_CSS)
                .with_header("Cache-Control", "no-store"),
        ),

        ("GET", "/licenses.txt") => Routed::Once(Response::text(200, assets::ICON_LICENSE)),
        ("GET", path) if path.starts_with("/icons/") => {
            Routed::Once(match assets::icon(&path[7..]) {
                Some(svg) => Response::new(200, "image/svg+xml", svg),
                None => Response::error(404, "Unknown icon"),
            })
        }
        ("GET", "/api/state") => Routed::Once(Response::json(200, &state_json(shell))),
        ("GET", "/api/preview") => {
            let active = shell.preview.lock().unwrap_or_else(|e| e.into_inner());
            let value = match active.as_ref() {
                Some(preview) => Project::open(&preview.project)
                    .map_err(|e| e.to_string())
                    .and_then(|project| preview.freshness(&project)),
                None => Ok(serde_json::json!({"ok":true,"active":false})),
            };
            Routed::Once(match value {
                Ok(value) => Response::json(200, &value),
                Err(error) => Response::json(400, &serde_json::json!({"ok":false,"error":error})),
            })
        }
        ("POST", "/api/preview") => {
            let result = (|| -> Result<serde_json::Value, String> {
                let input: serde_json::Value =
                    serde_json::from_slice(&request.body).map_err(|e| e.to_string())?;
                let mut active = shell.preview.lock().unwrap_or_else(|e| e.into_inner());
                if input["action"] == "stop" {
                    shell.preview_epoch.fetch_add(1, Ordering::SeqCst);
                    active.take();
                    shell
                        .fallback_preview
                        .lock()
                        .unwrap_or_else(|e| e.into_inner())
                        .take();
                    return Ok(serde_json::json!({"ok":true,"stopped":true}));
                }
                if matches!(input["action"].as_str(), Some("commit" | "rollback")) {
                    let current = active.as_ref().ok_or("No active preview")?;
                    if current.describe(true)["session"] != input["session"] {
                        return Err(
                            "Preview changed before confirmation; nothing was replaced".into()
                        );
                    }
                    let mut fallback = shell
                        .fallback_preview
                        .lock()
                        .unwrap_or_else(|e| e.into_inner());
                    if input["action"] == "rollback" {
                        let previous = fallback
                            .take()
                            .ok_or("There is no previous preview to restore")?;
                        *active = Some(previous);
                        shell.preview_epoch.fetch_add(1, Ordering::SeqCst);
                        return Ok(active.as_ref().unwrap().describe(true));
                    }
                    fallback.take();
                    return Ok(serde_json::json!({"ok":true,"committed":true}));
                }
                if input.get("force").is_some_and(|v| !v.is_boolean()) {
                    return Err("'force' must be a boolean".into());
                }
                let root = input
                    .get("project")
                    .and_then(serde_json::Value::as_str)
                    .map(PathBuf::from)
                    .unwrap_or_else(|| selected_root(shell));
                let project = Project::open(&root).map_err(|e| e.to_string())?;
                if input["action"] == "export" {
                    drop(active);
                    let origin = format!("http://127.0.0.1:{}", shell.port);
                    let fresh =
                        preview::Preview::build(&project, shell.godot_hint.as_deref(), &origin)?;
                    return fresh.export_bundle(input["output"].as_str().unwrap_or("dist/web"));
                }
                if input["force"] != true {
                    if let Some(preview) = active.as_ref().filter(|p| p.project == project.root) {
                        if preview.is_fresh(&project)? {
                            return Ok(preview.describe(true));
                        }
                    }
                }
                let default_origin = format!("http://127.0.0.1:{}", shell.port);
                let origin = request.header("origin").unwrap_or(&default_origin);
                let previous_session = active.as_ref().map(|p| p.describe(true)["session"].clone());
                let previous_epoch = shell.preview_epoch.load(Ordering::SeqCst);
                drop(active);
                let preview =
                    preview::Preview::build(&project, shell.godot_hint.as_deref(), origin)?;
                let result = preview.describe(false);
                let mut active = shell.preview.lock().unwrap_or_else(|e| e.into_inner());
                if !shell.running.load(Ordering::SeqCst)
                    || shell.preview_epoch.load(Ordering::SeqCst) != previous_epoch
                    || active.as_ref().map(|p| p.describe(true)["session"].clone())
                        != previous_session
                {
                    return Err("Another client changed the preview during this build; the active preview was preserved".into());
                }
                *shell
                    .fallback_preview
                    .lock()
                    .unwrap_or_else(|e| e.into_inner()) = active.replace(preview);
                shell.preview_epoch.fetch_add(1, Ordering::SeqCst);
                Ok(result)
            })();
            Routed::Once(match result {
                Ok(value) => Response::json(200, &value),
                Err(error) => Response::json(400, &serde_json::json!({"ok":false,"error":error})),
            })
        }
        ("GET", "/api/projects") => Routed::Once(projects_response(shell, None)),
        ("POST", "/api/projects") => Routed::Once(projects_response(shell, Some(request))),
        ("POST", "/api/project") => {
            let result = serde_json::from_slice::<serde_json::Value>(&request.body)
                .map_err(|e| e.to_string())
                .and_then(|input| {
                    let root = input
                        .get("project")
                        .and_then(serde_json::Value::as_str)
                        .map(PathBuf::from)
                        .unwrap_or_else(|| selected_root(shell));
                    aurum_studio_core::project_ops::execute(&root, &input, false)
                });
            Routed::Once(match result {
                Ok(value) => Response::json(200, &value),
                Err(message) => {
                    Response::json(400, &serde_json::json!({"ok":false,"error":message}))
                }
            })
        }
        ("GET", "/api/agent") => {
            let command = std::env::current_exe()
                .map(|path| path.display().to_string())
                .unwrap_or_else(|_| "aurum".into());
            Routed::Once(Response::json(
                200,
                &serde_json::json!({"mcpServers":{"aurum":{"command":command,"args":["mcp","--root",selected_root(shell),"--tools","studio"]}}}),
            ))
        }

        ("POST", "/api/command") => Routed::Once(handle_command(request, &shell.supervisor)),

        ("GET", "/api/events") => {
            let (id, receiver) = shell.hub.subscribe();
            Routed::Stream { id, receiver }
        }

        ("POST", "/api/stop") => {
            if shell.operations.load(Ordering::SeqCst) > 0 || shell.supervisor.is_busy() {
                return Routed::Once(Response::error(
                    409,
                    "An operation is still running. Wait for it to finish before closing Studio.",
                ));
            }
            shell.running.store(false, Ordering::SeqCst);
            Routed::Once(Response::json(200, &serde_json::json!({"stopped": true})))
        }

        ("GET", path) if path.starts_with("/api/") => {
            Routed::Once(Response::error(404, "no such endpoint\n"))
        }
        ("GET", _) => Routed::Once(Response::error(404, "not found\n")),
        _ => Routed::Once(Response::error(405, "method not allowed\n")),
    }
}

/// Turn a posted command into a supervisor command.
fn handle_command(request: &Request, supervisor: &Arc<Supervisor>) -> Response {
    let parsed: serde_json::Value = match serde_json::from_slice(&request.body) {
        Ok(value) => value,
        Err(error) => return Response::error(400, format!("invalid JSON: {error}\n")),
    };

    let name = match parsed.get("command").and_then(|value| value.as_str()) {
        Some(name) => name,
        None => return Response::error(400, "the body needs a 'command' string\n"),
    };

    let command = match name {
        "doctor" => Command::Doctor,
        "develop" => Command::Develop { editor: false },
        "end-develop" => Command::EndDevelop,
        "restart-editor" => Command::RestartEditor,
        "build" => Command::Build {
            force: parsed
                .get("force")
                .and_then(|value| value.as_bool())
                .unwrap_or(false),
            release: parsed
                .get("release")
                .and_then(|value| value.as_bool())
                .unwrap_or(false),
        },
        "start-editor" => Command::StartEditor,
        "start-game" => Command::StartGame,
        "stop" => Command::Stop {
            force: parsed
                .get("force")
                .and_then(|value| value.as_bool())
                .unwrap_or(false),
        },
        other => {
            return Response::error(400, format!("unknown command '{other}'\n"));
        }
    };

    if supervisor.send(command) {
        Response::json(200, &serde_json::json!({"accepted": true}))
    } else {
        // Reported rather than silently dropped, so a page never waits for a
        // result that cannot arrive.
        Response::error(503, "the supervisor has stopped\n")
    }
}

/// A snapshot of what the shell knows without waiting for an event.
///
/// The page loads before the first event arrives, so it needs one request that
/// answers "what am I looking at" rather than an empty screen.
fn state_json(shell: &Arc<Shell>) -> serde_json::Value {
    let selected = selected_root(shell);
    let project = Project::open(&selected).ok();
    let godot_directory = project.as_ref().and_then(|project| {
        project
            .godot_project_dir()
            .and_then(|path| path.strip_prefix(&project.root).ok())
            .map(|path| path.to_string_lossy().replace('\\', "/"))
    });
    let native_package = project
        .as_ref()
        .and_then(|project| project.config.rust_package.clone());
    serde_json::json!({
        "studio": env!("CARGO_PKG_VERSION"),
        "project": project.map(|p|p.config.name).unwrap_or_else(||shell.project_name.clone()),
        "root": selected.to_str().unwrap_or(&shell.project_root),
        "native_package": native_package,
        "godot_directory": godot_directory,
    })
}

fn selected_root(shell: &Shell) -> PathBuf {
    shell
        .selected_root
        .lock()
        .unwrap_or_else(|error| error.into_inner())
        .clone()
}

fn projects_response(shell: &Arc<Shell>, request: Option<&Request>) -> Response {
    use aurum_studio_core::{templates, Registry};
    let result = (|| -> Result<serde_json::Value, String> {
        let registry_path =
            Registry::resolve_path().ok_or("Studio state directory is not configured")?;
        let mut registry = Registry::load(&registry_path).map_err(|e| e.to_string())?;
        if let Some(request) = request {
            let input: serde_json::Value =
                serde_json::from_slice(&request.body).map_err(|e| e.to_string())?;
            let path = PathBuf::from(input["path"].as_str().ok_or("project path is required")?);
            let action = input["action"].as_str().ok_or("action is required")?;
            if action == "create" {
                let name = input["name"].as_str().ok_or("project name is required")?;
                let template = input["template"].as_str().unwrap_or("3d");
                if !matches!(template, "2d" | "3d") {
                    return Err("Studio offers the 2d and 3d templates".into());
                }
                templates::create(
                    &path,
                    &templates::NewProject {
                        name: name.into(),
                        template: template.into(),
                        engine: selected_root(shell),
                    },
                )
                .map_err(|e| e.to_string())?;
            }
            if action == "forget" {
                registry.remove(&path.display().to_string());
            } else if matches!(action, "create" | "import" | "select") {
                let project = if action == "import" {
                    Project::import(&path)
                } else {
                    Project::open(&path)
                }
                .map_err(|e| e.to_string())?;
                registry.register(&project.config.name, &project.root);
                if !shell
                    .supervisor
                    .send(Command::SelectProject(project.root.clone()))
                {
                    return Err("supervisor is not running".into());
                }
                *shell
                    .selected_root
                    .lock()
                    .unwrap_or_else(|e| e.into_inner()) = project.root;
            } else {
                return Err("unknown project action".into());
            }
            registry.save(&registry_path).map_err(|e| e.to_string())?;
        }
        Ok(
            serde_json::json!({"projects":registry.projects,"selected":selected_root(shell),"templates":["2d","3d"]}),
        )
    })();
    match result {
        Ok(value) => Response::json(200, &value),
        Err(error) => Response::json(400, &serde_json::json!({"ok":false,"error":error})),
    }
}

/// Write an event stream until the client goes away.
fn stream_events(
    writer: &mut TcpStream,
    receiver: Receiver<Event>,
    running: &Arc<AtomicBool>,
) -> std::io::Result<()> {
    writer.write_all(
        b"HTTP/1.1 200 OK\r\nContent-Type: text/event-stream\r\nCache-Control: no-store\r\n\
          Connection: keep-alive\r\nX-Accel-Buffering: no\r\n\r\n",
    )?;
    writer.flush()?;

    // A first comment tells the browser the stream is open before anything
    // happens, so the page can show "connected" rather than "connecting".
    writer.write_all(b": connected\n\n")?;
    writer.flush()?;

    loop {
        if !running.load(Ordering::SeqCst) {
            // Sent as an ordinary message rather than a named event, so the
            // page's normal handler sees it. A named event needs its own
            // listener, and the page would miss the one message that says why
            // the stream is about to end.
            let _ = writer.write_all(b"data: {\"kind\":\"stopped\"}\n\n");
            let _ = writer.flush();
            return Ok(());
        }

        match receiver.recv_timeout(KEEPALIVE) {
            Ok(event) => {
                let payload =
                    serde_json::to_string(&event_json(&event)).unwrap_or_else(|_| "{}".to_string());
                // A newline inside the payload would end the frame early, so
                // the JSON is written as a single line and any newline in a
                // message is escaped by the encoder.
                if writer
                    .write_all(format!("data: {payload}\n\n").as_bytes())
                    .is_err()
                {
                    // The page closed. Not an error.
                    return Ok(());
                }
                if writer.flush().is_err() {
                    return Ok(());
                }
                if matches!(event, Event::Stopped) {
                    return Ok(());
                }
            }
            Err(mpsc::RecvTimeoutError::Timeout) => {
                if writer.write_all(b": keep-alive\n\n").is_err() {
                    return Ok(());
                }
                let _ = writer.flush();
            }
            Err(mpsc::RecvTimeoutError::Disconnected) => return Ok(()),
        }
    }
}

/// An event as the page sees it.
///
/// Written by hand rather than derived, so the shape the browser consumes is a
/// deliberate interface rather than a consequence of Rust's field names. The
/// match is exhaustive, so adding an event variant stops this compiling until
/// it has a wire form.
pub fn event_json(event: &Event) -> serde_json::Value {
    use serde_json::json;
    match event {
        Event::Health {
            verdict,
            summary,
            findings,
        } => json!({
            "kind": "health",
            "verdict": verdict.label(),
            "summary": summary,
            "findings": findings
                .iter()
                .map(|finding| json!({
                    "id": finding.id,
                    "health": finding.health.label(),
                    "summary": finding.summary,
                    "evidence": finding.evidence,
                    "remedy": finding.remedy,
                }))
                .collect::<Vec<serde_json::Value>>(),
        }),
        Event::BuildStarted { package, profile } => json!({
            "kind": "build-started",
            "package": package,
            "profile": profile,
        }),
        Event::BuildFinished {
            ok,
            summary,
            installed_sha256,
        } => json!({
            "kind": "build-finished",
            "ok": ok,
            "summary": summary,
            "sha256": installed_sha256,
        }),
        Event::ProcessStarted { kind, pid } => json!({
            "kind": "process-started",
            "process": kind.label(),
            "pid": pid,
        }),
        Event::ProcessStopped { kind, description } => json!({
            "kind": "process-stopped",
            "process": kind.label(),
            "description": description,
        }),
        Event::ChangeClassified { verdict, reason } => json!({
            "kind": "change",
            "verdict": verdict.label(),
            "reason": reason,
        }),
        Event::Log(line) => json!({ "kind": "log", "line": line }),
        Event::Error(message) => json!({ "kind": "error", "message": message }),
        Event::Stopped => json!({ "kind": "stopped" }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn another_loopback_port_cannot_control_studio_with_its_cookie() {
        let mut request = Request {
            method: "POST".into(),
            path: "/api/project".into(),
            query: Vec::new(),
            headers: vec![
                ("host".into(), "127.0.0.1:9000".into()),
                ("cookie".into(), "aurum_session=secret".into()),
                ("origin".into(), "http://127.0.0.1:9001".into()),
            ],
            body: Vec::new(),
        };
        assert!(check_token(&request, "secret").is_ok());
        assert_eq!(check_origin(&request, 9000).unwrap_err().status, 403);
        request.headers.retain(|(key, _)| key != "origin");
        request
            .headers
            .push(("sec-fetch-site".into(), "same-site".into()));
        assert!(check_origin(&request, 9000).is_err());
        request.headers.retain(|(key, _)| key != "sec-fetch-site");
        request
            .headers
            .push(("origin".into(), "http://127.0.0.1:9000".into()));
        assert!(check_origin(&request, 9000).is_ok());
    }

    #[test]
    fn a_matching_token_is_accepted() {
        let mut request = Request {
            method: "GET".into(),
            path: "/".into(),
            query: Vec::new(),
            headers: Vec::new(),
            body: Vec::new(),
        };
        request
            .headers
            .push(("x-aurum-token".into(), "secret".into()));
        assert!(check_token(&request, "secret").is_ok());
    }

    #[test]
    fn a_wrong_token_is_refused() {
        let mut request = Request {
            method: "GET".into(),
            path: "/".into(),
            query: Vec::new(),
            headers: Vec::new(),
            body: Vec::new(),
        };
        request
            .headers
            .push(("x-aurum-token".into(), "guess".into()));
        let response = check_token(&request, "secret").unwrap_err();
        assert_eq!(response.status, 401);
    }

    #[test]
    fn a_missing_token_is_refused() {
        let request = Request {
            method: "GET".into(),
            path: "/".into(),
            query: Vec::new(),
            headers: Vec::new(),
            body: Vec::new(),
        };
        assert_eq!(check_token(&request, "secret").unwrap_err().status, 401);
    }

    #[test]
    fn a_token_of_the_wrong_length_is_refused_without_panicking() {
        // The length check happens first, so a short or long guess cannot
        // index past the end of the real token.
        let short = Request {
            method: "GET".into(),
            path: "/".into(),
            query: vec![("t".into(), "s".into())],
            headers: Vec::new(),
            body: Vec::new(),
        };
        assert!(check_token(&short, "secret").is_err());

        let long = Request {
            method: "GET".into(),
            path: "/".into(),
            query: vec![("t".into(), "secret-and-more".into())],
            headers: Vec::new(),
            body: Vec::new(),
        };
        assert!(check_token(&long, "secret").is_err());
    }

    #[test]
    fn the_token_may_arrive_in_the_query_for_the_first_page_load() {
        let request = Request {
            method: "GET".into(),
            path: "/".into(),
            query: vec![("t".into(), "secret".into())],
            headers: Vec::new(),
            body: Vec::new(),
        };
        assert!(check_token(&request, "secret").is_ok());
    }

    #[test]
    fn the_header_wins_over_the_query_string() {
        // Otherwise a page could append a guessed token to a URL that already
        // carried the right one, or the reverse, and the check and the use
        // would disagree about which was meant.
        let request = Request {
            method: "GET".into(),
            path: "/".into(),
            query: vec![("t".into(), "secret".into())],
            headers: vec![("x-aurum-token".into(), "wrong".into())],
            body: Vec::new(),
        };
        assert!(check_token(&request, "secret").is_err());
    }

    fn request_with_host(host: &str) -> Request {
        Request {
            method: "GET".into(),
            path: "/".into(),
            query: Vec::new(),
            headers: vec![("host".into(), host.into())],
            body: Vec::new(),
        }
    }

    #[test]
    fn loopback_hosts_are_accepted() {
        for host in [
            "127.0.0.1:8080",
            "127.0.0.1",
            "localhost:8080",
            "localhost",
            "[::1]:8080",
            "[::1]",
        ] {
            assert!(
                check_local(&request_with_host(host)).is_ok(),
                "'{host}' should be accepted"
            );
        }
    }

    #[test]
    fn a_foreign_host_is_refused() {
        // The DNS-rebinding case: a hostile domain resolving to 127.0.0.1.
        for host in ["evil.example", "evil.example:8080", "10.0.0.5", "0.0.0.0"] {
            let response = check_local(&request_with_host(host)).unwrap_err();
            assert_eq!(response.status, 403, "'{host}' should be refused");
        }
    }

    #[test]
    fn a_request_without_a_host_header_is_refused() {
        let request = Request {
            method: "GET".into(),
            path: "/".into(),
            query: Vec::new(),
            headers: Vec::new(),
            body: Vec::new(),
        };
        assert_eq!(check_local(&request).unwrap_err().status, 400);
    }

    #[test]
    fn a_host_that_looks_like_loopback_but_is_not_is_refused() {
        // `127.0.0.1.evil.example` resolves wherever its owner says, and a
        // prefix check would wrongly accept it.
        for host in ["127.0.0.1.evil.example", "localhost.evil.example"] {
            assert!(
                check_local(&request_with_host(host)).is_err(),
                "'{host}' should be refused"
            );
        }
    }

    #[test]
    fn constant_time_comparison_agrees_with_equality() {
        assert!(constant_time_eq("abc", "abc"));
        assert!(!constant_time_eq("abc", "abd"));
        assert!(!constant_time_eq("abc", "ab"));
        assert!(!constant_time_eq("", "a"));
        assert!(constant_time_eq("", ""));
    }

    #[test]
    fn the_fan_out_drops_only_the_clients_that_went_away() {
        let hub = Arc::new(Hub::default());
        let (first, first_rx) = hub.subscribe();
        let (_second, second_rx) = hub.subscribe();

        hub.broadcast(&Event::Stopped);
        assert_eq!(first_rx.recv().unwrap(), Event::Stopped);
        assert_eq!(second_rx.recv().unwrap(), Event::Stopped);

        // A client that stops listening is removed on the next broadcast.
        drop(first_rx);
        hub.unsubscribe(first);
        hub.broadcast(&Event::Error("x".into()));

        let clients = hub.clients.lock().unwrap();
        assert_eq!(clients.len(), 1, "the departed client should be gone");
    }

    #[test]
    fn a_broadcast_reaches_every_subscriber() {
        let hub = Arc::new(Hub::default());
        let (_a, a_rx) = hub.subscribe();
        let (_b, b_rx) = hub.subscribe();
        let (_c, c_rx) = hub.subscribe();

        hub.broadcast(&Event::Log("hello".into()));

        for receiver in [a_rx, b_rx, c_rx] {
            assert_eq!(receiver.recv().unwrap(), Event::Log("hello".into()));
        }
    }

    #[test]
    fn every_event_has_a_wire_form_with_a_kind() {
        let events = vec![
            Event::Health {
                verdict: aurum_studio_core::doctor::Health::Healthy,
                summary: "s".into(),
                findings: Vec::new(),
            },
            Event::BuildStarted {
                package: "p".into(),
                profile: "debug",
            },
            Event::BuildFinished {
                ok: true,
                summary: "s".into(),
                installed_sha256: Some("abc".into()),
            },
            Event::ProcessStarted {
                kind: aurum_studio_core::ProcessKind::Editor,
                pid: 1,
            },
            Event::ProcessStopped {
                kind: aurum_studio_core::ProcessKind::Game,
                description: "d".into(),
            },
            Event::ChangeClassified {
                verdict: aurum_studio_core::Verdict::Reload,
                reason: "r".into(),
            },
            Event::Log("l".into()),
            Event::Error("e".into()),
            Event::Stopped,
        ];

        for event in events {
            let json = event_json(&event);
            assert!(
                json.get("kind").and_then(|value| value.as_str()).is_some(),
                "{event:?} needs a kind"
            );
        }
    }

    #[test]
    fn a_health_event_carries_every_finding_to_the_page() {
        use aurum_studio_core::doctor::{Finding, Health};

        // In the order the supervisor sends them: problems first.
        let event = Event::Health {
            verdict: Health::Blocked,
            summary: "9 ok, 0 warnings, 1 blocked".into(),
            findings: vec![
                Finding {
                    id: "cargo_manifest",
                    health: Health::Blocked,
                    summary: "no Cargo.toml at the project root".into(),
                    evidence: None,
                    remedy: Some("add a workspace manifest".into()),
                },
                Finding {
                    id: "cargo",
                    health: Health::Healthy,
                    summary: "Cargo available".into(),
                    evidence: Some("/tools/cargo (1.95.0)".into()),
                    remedy: None,
                },
            ],
        };

        let json = event_json(&event);
        assert_eq!(json["kind"], "health");
        assert_eq!(json["verdict"], "blocked");
        assert_eq!(json["summary"], "9 ok, 0 warnings, 1 blocked");

        let findings = json["findings"]
            .as_array()
            .expect("the findings should be a list the page can walk");
        assert_eq!(
            findings.len(),
            2,
            "no finding may be dropped on the way out"
        );
        assert_eq!(findings[0]["id"], "cargo_manifest");
        assert_eq!(findings[0]["health"], "blocked");
        assert_eq!(findings[0]["summary"], "no Cargo.toml at the project root");
        assert_eq!(findings[0]["remedy"], "add a workspace manifest");
        assert!(
            findings[0]["evidence"].is_null(),
            "a finding with nothing to show says so rather than inventing it"
        );
        assert_eq!(findings[1]["evidence"], "/tools/cargo (1.95.0)");
        assert!(findings[1]["remedy"].is_null());
    }

    #[test]
    fn a_log_line_with_newlines_stays_one_json_string() {
        // The event stream is line-framed, so a newline in a payload must be
        // escaped rather than emitted, which would split the frame.
        let encoded =
            serde_json::to_string(&event_json(&Event::Log("first\nsecond\nthird".into()))).unwrap();
        assert_eq!(encoded.lines().count(), 1);
        assert!(encoded.contains("first\\nsecond"));
    }

    #[test]
    fn a_command_json_body_maps_to_the_right_command() {
        // Exercised through `handle_command` by way of a real supervisor, so
        // this also covers that an accepted command is actually delivered.
        let root = std::env::temp_dir().join(format!("aurum-server-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).unwrap();
        std::fs::write(
            root.join("aurum.toml"),
            "schema_version = 1\nname = \"t\"\n",
        )
        .unwrap();
        let project = Project::open(&root).unwrap();

        let supervisor = Arc::new(Supervisor::start(SupervisorConfig::new(project, None)));
        let request = Request {
            method: "POST".into(),
            path: "/api/command".into(),
            query: Vec::new(),
            headers: Vec::new(),
            body: br#"{"command":"doctor"}"#.to_vec(),
        };
        let response = handle_command(&request, &supervisor);
        assert_eq!(response.status, 200);

        // Dropping the last handle stops the worker through its Drop impl.
        drop(supervisor);
    }

    #[test]
    fn an_unknown_command_is_refused_by_name() {
        let root =
            std::env::temp_dir().join(format!("aurum-server-unknown-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).unwrap();
        std::fs::write(
            root.join("aurum.toml"),
            "schema_version = 1\nname = \"t\"\n",
        )
        .unwrap();
        let project = Project::open(&root).unwrap();

        let supervisor = Arc::new(Supervisor::start(SupervisorConfig::new(project, None)));
        let request = Request {
            method: "POST".into(),
            path: "/api/command".into(),
            query: Vec::new(),
            headers: Vec::new(),
            body: br#"{"command":"launch-missiles"}"#.to_vec(),
        };
        let response = handle_command(&request, &supervisor);
        assert_eq!(response.status, 400);

        // Dropping the last handle stops the worker through its Drop impl.
        drop(supervisor);
    }

    #[test]
    fn a_body_that_is_not_json_is_refused() {
        let root = std::env::temp_dir().join(format!("aurum-server-bad-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).unwrap();
        std::fs::write(
            root.join("aurum.toml"),
            "schema_version = 1\nname = \"t\"\n",
        )
        .unwrap();
        let project = Project::open(&root).unwrap();

        let supervisor = Arc::new(Supervisor::start(SupervisorConfig::new(project, None)));
        let request = Request {
            method: "POST".into(),
            path: "/api/command".into(),
            query: Vec::new(),
            headers: Vec::new(),
            body: b"not json".to_vec(),
        };
        assert_eq!(handle_command(&request, &supervisor).status, 400);

        // Dropping the last handle stops the worker through its Drop impl.
        drop(supervisor);
    }

    // -- a real server on a real socket -----------------------------------

    /// A project that opens, so a server can be started against it.
    fn temporary_project(tag: &str) -> Project {
        let root = std::env::temp_dir().join(format!("aurum-server-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).unwrap();
        std::fs::write(
            root.join("aurum.toml"),
            "schema_version = 1\nname = \"t\"\n",
        )
        .unwrap();
        std::fs::write(root.join("project.godot"), "config_version=5\n").unwrap();
        Project::open(&root).unwrap()
    }

    /// A raw HTTP exchange against a live server, returning the whole reply.
    ///
    /// Deliberately hand-written rather than using an HTTP client: the point
    /// is to exercise the bytes a browser would send.
    fn exchange(port: u16, request: &str) -> String {
        use std::io::Read;
        let mut stream = TcpStream::connect(("127.0.0.1", port)).expect("connect");
        stream
            .set_read_timeout(Some(Duration::from_secs(10)))
            .unwrap();
        stream.write_all(request.as_bytes()).expect("write");
        stream.flush().unwrap();
        let mut reply = String::new();
        let _ = stream.read_to_string(&mut reply);
        reply
    }

    /// Read from a stream until `wanted` appears, or the deadline passes.
    ///
    /// A single `read` is not enough for a stream: the headers and the first
    /// comment are separate writes, so TCP is free to deliver them in separate
    /// segments and a test that reads once would fail intermittently.
    fn read_until(stream: &mut TcpStream, wanted: &str, timeout: Duration) -> String {
        use std::io::Read;
        let mut seen = String::new();
        let deadline = std::time::Instant::now() + timeout;
        let mut buffer = [0u8; 2048];
        while !seen.contains(wanted) && std::time::Instant::now() < deadline {
            match stream.read(&mut buffer) {
                Ok(0) => break,
                Ok(count) => seen.push_str(&String::from_utf8_lossy(&buffer[..count])),
                Err(_) => break,
            }
        }
        seen
    }

    fn start_server(tag: &str) -> (Arc<Server>, std::thread::JoinHandle<()>) {
        let server = Arc::new(Server::bind(ServerConfig::new(temporary_project(tag))).unwrap());
        let serving = Arc::clone(&server);
        let handle = std::thread::spawn(move || serving.serve());
        (server, handle)
    }

    #[test]
    fn it_binds_loopback_and_nothing_else() {
        let (server, handle) = start_server("bind");
        assert!(
            server.local_addr().ip().is_loopback(),
            "the shell must bind the loopback interface, got {}",
            server.local_addr()
        );
        server.stop();
        handle.join().unwrap();
    }

    #[test]
    fn an_ephemeral_port_is_chosen_when_zero_is_asked_for() {
        let (server, handle) = start_server("port");
        assert_ne!(server.port(), 0, "a real port should have been assigned");
        server.stop();
        handle.join().unwrap();
    }

    #[test]
    fn a_request_without_a_token_is_refused_over_a_real_socket() {
        let (server, handle) = start_server("notoken");
        let reply = exchange(
            server.port(),
            "GET /api/state HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n",
        );
        assert!(
            reply.starts_with("HTTP/1.1 401"),
            "expected a refusal, got:\n{reply}"
        );
        server.stop();
        handle.join().unwrap();
    }

    #[test]
    fn a_request_with_the_token_is_served_over_a_real_socket() {
        let (server, handle) = start_server("withtoken");
        let request = format!(
            "GET /api/state HTTP/1.1\r\nHost: 127.0.0.1:{}\r\nX-Aurum-Token: {}\r\n\r\n",
            server.port(),
            server.token()
        );
        let reply = exchange(server.port(), &request);
        assert!(
            reply.starts_with("HTTP/1.1 200"),
            "expected success, got:\n{reply}"
        );
        assert!(reply.contains("\"studio\""));
        assert!(
            reply.contains("\"project\":\"t\""),
            "the snapshot should name the project, got:\n{reply}"
        );
        server.stop();
        handle.join().unwrap();
    }

    #[test]
    fn the_page_is_served_and_carries_no_token() {
        let (server, handle) = start_server("page");
        let request = format!(
            "GET /?t={} HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n",
            server.token()
        );
        let reply = exchange(server.port(), &request);
        assert!(reply.starts_with("HTTP/1.1 200"));
        assert!(reply.contains("text/html"));

        // The token is now legitimately in the `Set-Cookie` header, because
        // that is how a browser is given it — headers are where credentials
        // belong. What must never happen is the token being written into the
        // document itself, where it would sit in view-source, in any cache of
        // the page, and in anything that saves the HTML.
        let body = reply.split("\r\n\r\n").nth(1).unwrap_or_default();
        assert!(
            !body.contains(server.token()),
            "the token must not be baked into the page body"
        );

        server.stop();
        handle.join().unwrap();
    }

    #[test]
    fn a_command_posted_over_a_real_socket_is_accepted() {
        let (server, handle) = start_server("command");
        let body = br#"{"command":"doctor"}"#;
        let request = format!(
            "POST /api/command HTTP/1.1\r\nHost: 127.0.0.1\r\nX-Aurum-Token: {}\r\n\
             Content-Type: application/json\r\nContent-Length: {}\r\n\r\n{}",
            server.token(),
            body.len(),
            String::from_utf8_lossy(body)
        );
        let reply = exchange(server.port(), &request);
        assert!(
            reply.starts_with("HTTP/1.1 200"),
            "expected acceptance, got:\n{reply}"
        );
        assert!(reply.contains("accepted"));
        server.stop();
        handle.join().unwrap();
    }

    /// The cookie value a reply asked the browser to store.
    fn set_cookie(reply: &str) -> Option<String> {
        reply
            .lines()
            .find_map(|line| line.strip_prefix("Set-Cookie: "))
            .and_then(|value| value.split(';').next())
            .map(str::to_string)
    }

    #[test]
    fn the_page_can_fetch_its_own_assets_the_way_a_browser_does() {
        // The bug this exists for. A browser fetches the stylesheet and the
        // script as *separate requests* that carry no query string and no
        // custom header — only cookies. Every earlier test sent the token
        // explicitly, which is not what a browser does, so the whole suite
        // passed while the page rendered as unstyled text with an enormous
        // SVG where the wordmark's mark should have been.
        let (server, handle) = start_server("subresources");

        let page = exchange(
            server.port(),
            &format!(
                "GET /?t={} HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n",
                server.token()
            ),
        );
        assert!(page.starts_with("HTTP/1.1 200"), "got:\n{page}");
        let cookie = set_cookie(&page).expect("the page load should plant a session cookie");

        for asset in ["/style.css", "/app.js"] {
            let reply = exchange(
                server.port(),
                &format!("GET {asset} HTTP/1.1\r\nHost: 127.0.0.1\r\nCookie: {cookie}\r\n\r\n"),
            );
            assert!(
                reply.starts_with("HTTP/1.1 200"),
                "{asset} must load for the page itself, or nothing is styled, got:\n{reply}"
            );
        }

        // And the assets really are the stylesheet and the script, not a
        // refusal body that happens to carry the right status.
        let css = exchange(
            server.port(),
            &format!("GET /style.css HTTP/1.1\r\nHost: 127.0.0.1\r\nCookie: {cookie}\r\n\r\n"),
        );
        assert!(css.contains(".verdict.ok"), "the stylesheet should be real");

        server.stop();
        handle.join().unwrap();
    }

    #[test]
    fn a_cookie_still_has_to_be_the_right_token() {
        let (server, handle) = start_server("badcookie");
        let reply = exchange(
            server.port(),
            &format!(
                "GET /api/state HTTP/1.1\r\nHost: 127.0.0.1\r\nCookie: {TOKEN_COOKIE}=nonsense\r\n\r\n"
            ),
        );
        assert!(
            reply.starts_with("HTTP/1.1 401"),
            "a guessed cookie is still a guess, got:\n{reply}"
        );
        server.stop();
        handle.join().unwrap();
    }

    #[test]
    fn the_session_cookie_is_httponly_and_same_site() {
        // HttpOnly keeps an injected script from reading the token; Strict
        // means a cross-site request arriving with it is not to be honoured.
        let (server, handle) = start_server("cookieflags");
        let page = exchange(
            server.port(),
            &format!(
                "GET /?t={} HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n",
                server.token()
            ),
        );
        let header = page
            .lines()
            .find(|line| line.starts_with("Set-Cookie: "))
            .expect("a cookie should be set");
        assert!(header.contains("HttpOnly"), "got:\n{header}");
        assert!(header.contains("SameSite=Strict"), "got:\n{header}");
        assert!(header.contains("Path=/"), "got:\n{header}");
        server.stop();
        handle.join().unwrap();
    }

    #[test]
    fn an_empty_header_falls_through_to_the_cookie() {
        // The page sends its header from sessionStorage, which is empty when
        // somebody opens the address without a token. An empty value must not
        // shadow the cookie that would have worked.
        let (server, handle) = start_server("emptytoken");
        let reply = exchange(
            server.port(),
            &format!(
                "GET /api/state HTTP/1.1\r\nHost: 127.0.0.1\r\nX-Aurum-Token: \r\n\
                 Cookie: {TOKEN_COOKIE}={}\r\n\r\n",
                server.token()
            ),
        );
        assert!(
            reply.starts_with("HTTP/1.1 200"),
            "an empty header should fall through, got:\n{reply}"
        );
        server.stop();
        handle.join().unwrap();
    }

    #[test]
    fn the_event_stream_opens_and_announces_itself() {
        use std::io::Write as _;
        let (server, handle) = start_server("events");

        let mut stream = TcpStream::connect(("127.0.0.1", server.port())).unwrap();
        stream
            .set_read_timeout(Some(Duration::from_secs(10)))
            .unwrap();
        let request = format!(
            "GET /api/events HTTP/1.1\r\nHost: 127.0.0.1\r\nX-Aurum-Token: {}\r\n\r\n",
            server.token()
        );
        stream.write_all(request.as_bytes()).unwrap();
        stream.flush().unwrap();

        let head = read_until(&mut stream, ": connected", Duration::from_secs(10));
        assert!(head.starts_with("HTTP/1.1 200"), "got:\n{head}");
        assert!(head.contains("text/event-stream"));
        assert!(
            head.contains(": connected"),
            "the stream should announce itself, got:\n{head}"
        );

        drop(stream);
        server.stop();
        handle.join().unwrap();
    }

    #[test]
    fn an_event_reaches_a_connected_stream() {
        use std::io::Write as _;
        let (server, handle) = start_server("streamevent");

        let mut stream = TcpStream::connect(("127.0.0.1", server.port())).unwrap();
        stream
            .set_read_timeout(Some(Duration::from_secs(10)))
            .unwrap();
        let request = format!(
            "GET /api/events HTTP/1.1\r\nHost: 127.0.0.1\r\nX-Aurum-Token: {}\r\n\r\n",
            server.token()
        );
        stream.write_all(request.as_bytes()).unwrap();
        stream.flush().unwrap();

        let head = read_until(&mut stream, ": connected", Duration::from_secs(10));
        assert!(head.contains(": connected"), "stream did not open:\n{head}");

        // Now ask for something and watch it arrive on the stream, without the
        // page asking for it again.
        let body = br#"{"command":"doctor"}"#;
        let post = format!(
            "POST /api/command HTTP/1.1\r\nHost: 127.0.0.1\r\nX-Aurum-Token: {}\r\n\
             Content-Length: {}\r\n\r\n{}",
            server.token(),
            body.len(),
            String::from_utf8_lossy(body)
        );
        let reply = exchange(server.port(), &post);
        assert!(reply.starts_with("HTTP/1.1 200"), "post failed:\n{reply}");

        let seen = read_until(&mut stream, "\"health\"", Duration::from_secs(30));
        assert!(
            seen.contains("\"health\""),
            "the health event should have been pushed, got:\n{seen}"
        );

        drop(stream);
        server.stop();
        handle.join().unwrap();
    }

    #[test]
    fn a_foreign_host_is_refused_over_a_real_socket_even_with_the_token() {
        let (server, handle) = start_server("rebind");
        let request = format!(
            "GET /api/state HTTP/1.1\r\nHost: evil.example\r\nX-Aurum-Token: {}\r\n\r\n",
            server.token()
        );
        let reply = exchange(server.port(), &request);
        assert!(
            reply.starts_with("HTTP/1.1 403"),
            "a rebinding attempt must be refused, got:\n{reply}"
        );
        server.stop();
        handle.join().unwrap();
    }

    #[test]
    fn an_unknown_path_is_a_404() {
        let (server, handle) = start_server("notfound");
        let request = format!(
            "GET /api/nope HTTP/1.1\r\nHost: 127.0.0.1\r\nX-Aurum-Token: {}\r\n\r\n",
            server.token()
        );
        let reply = exchange(server.port(), &request);
        assert!(reply.starts_with("HTTP/1.1 404"), "got:\n{reply}");
        server.stop();
        handle.join().unwrap();
    }

    #[test]
    fn stopping_the_server_finishes_the_accept_loop() {
        let (server, handle) = start_server("stop");
        server.stop();
        // A join that returns proves the loop noticed; if it did not, this
        // test would hang rather than fail.
        handle.join().unwrap();
    }

    #[test]
    fn the_stop_endpoint_finishes_the_accept_loop() {
        // The route the page's shut-down button calls. Verified live as well:
        // the process exited zero and the listener closed.
        let (server, handle) = start_server("apistop");
        let request = format!(
            "POST /api/stop HTTP/1.1\r\nHost: 127.0.0.1\r\nX-Aurum-Token: {}\r\n\
             Content-Length: 0\r\n\r\n",
            server.token()
        );
        let reply = exchange(server.port(), &request);
        assert!(reply.starts_with("HTTP/1.1 200"), "got:\n{reply}");
        assert!(reply.contains("stopped"));
        handle.join().unwrap();
    }

    #[test]
    fn the_stop_endpoint_needs_the_token_like_everything_else() {
        // It is the one route that takes the shell down, so it must not be
        // reachable by a page that merely knows the port.
        let (server, handle) = start_server("apistopauth");
        let reply = exchange(
            server.port(),
            "POST /api/stop HTTP/1.1\r\nHost: 127.0.0.1\r\nContent-Length: 0\r\n\r\n",
        );
        assert!(reply.starts_with("HTTP/1.1 401"), "got:\n{reply}");
        server.stop();
        handle.join().unwrap();
    }

    #[test]
    fn the_stopper_can_stop_from_another_thread() {
        let (server, handle) = start_server("stopper");
        let stopper = server.stopper();
        std::thread::spawn(move || {
            std::thread::sleep(Duration::from_millis(50));
            stopper.stop();
        });
        handle.join().unwrap();
    }

    #[test]
    fn the_url_carries_the_token_and_points_at_loopback() {
        let (server, handle) = start_server("url");
        let url = server.url();
        assert!(url.starts_with("http://127.0.0.1:"));
        assert!(url.contains(&format!("t={}", server.token())));
        server.stop();
        handle.join().unwrap();
    }
}
